title: Obsidian Git Docs
description: Οδηγός για σύνδεση Obsidian με Git
baseurl: "/ObsidianGitDocs"
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - README.md
  - LICENSE
